/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRoomRouteImport } from './routes/join-room'
import { Route as CreateRoomRouteImport } from './routes/create-room'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbyCodeRouteImport } from './routes/lobby.$code'

const JoinRoomRoute = JoinRoomRouteImport.update({
  id: '/join-room',
  path: '/join-room',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoomRoute = CreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/lobby/$code': typeof LobbyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/lobby/$code': typeof LobbyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/lobby/$code': typeof LobbyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-room' | '/join-room' | '/lobby/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-room' | '/join-room' | '/lobby/$code'
  id: '__root__' | '/' | '/create-room' | '/join-room' | '/lobby/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoomRoute: typeof CreateRoomRoute
  JoinRoomRoute: typeof JoinRoomRoute
  LobbyCodeRoute: typeof LobbyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join-room': {
      id: '/join-room'
      path: '/join-room'
      fullPath: '/join-room'
      preLoaderRoute: typeof JoinRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-room': {
      id: '/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof CreateRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoomRoute: CreateRoomRoute,
  JoinRoomRoute: JoinRoomRoute,
  LobbyCodeRoute: LobbyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
